### ISSUE TITLE
Ew.

### ISSUE THREAD

**Issue by Sxtanna** [timtomtim7/spigotkt-docs#1]

**Comment by timtomtim7** [comment]
Explain.

**Comment by Sxtanna** [comment]
You said I lied to you, so I just had to say something back.

**Comment by timtomtim7** [comment]
The MOTD of your server said "An Astra Server", it was clearly Bukkit.

**Comment by Sxtanna** [comment]
The issue with that is that it's a different Astra, and I never claimed it to not be Bukkit.
